### ISSUE TITLE
Round bracket in substitution text disapears

### ISSUE THREAD

**Issue by advisoft** [mrtazz/plustache#17]
When substituting an non-html escaped piece of text that has a round bracket, the round bracket does not make it into the rendered output.

Boost regex replace is eating the character and it cant be escaped because plustache escapes the regex escape character.

My quick fix was to escape both brackets at the sample place where the \ is getting escaped. (line 110ish of template.cpp on the current version)

This happens on BCC32 inside Rad Studio XE7.

Not sure if I am overlooking an obvious way around this?

Cheers

**Comment by chesles** [comment]
Same thing is happening to dollar signs. I added a couple failing test cases here: https://github.com/mrtazz/plustache/compare/master...chesles:dollar-sign

There is a PR (#19) for removing boost, not sure if that will solve this issue or not. @mrtazz any ideas on the best way to handle this?

**Comment by chesles** [comment]
Adding the `boost::regex_constants::format_literal` flag to the `regex_replace` call disables special handling of the replacement text, which I think in this case is the desired behavior. I made a PR adding this option to all `regex_replace` calls: #20
